/* eslint-disable global-require */
module.exports = {
    safelist: [
        'alignright', // Needs WP generated classes
        'alignleft',
        'aligncenter',
        'wp-caption',
        'wp-caption-text',
        '.gform_wrapper.gravity-theme .gfield_consent_description',
        '.gform_wrapper.gravity-theme .field_description_below .gfield_consent_description',
        'js-animate',
        'js-hidden',
        'js-stagger',
        'js-staggered',
        'lg:inline-flex',
        'lg:hidden',
        'grid',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'wp-block-table',
        'wp-block-columns',
        'overflow-x-auto',
        'is-style-stripes',
        'min-w-full',
        'is-style-narrow',
        'is-style-regular',
        'is-style-full',
        'is-style-wide',
        'opacity-0',
        'invisible',
        'responsive-nav',
        'dropdown-toggle',
        'sub-menu',
        'container',
        'max-w-screen-xl',
        'py-half',
        'splide',
        'splide__slide',
        'splide__list',
        'splide__pagination',
        'splide__video__play',
        'absolute-center',
        'vertical-center',
        'with-overlay',
        'absolute-cover',
        'clearfix',
        'mt-4',
        'flex',
        'flex-col',
        'md:grid-cols-2',
        'lg:grid-cols-3',
        'xl:grid-cols-4',
        'gap-1',
        'xl:gap-1.5',
        'aspect-[3/2]',
        'lg:aspect-[4/3]',
        '2xl:aspect-[16/7]',
        'lg:w-9/12',
        'lg:absolute-center',
        'basis-full',
        'lg:basis-1/2',
        'lg:flex',
        'lg:justify-center',
        'lg:flex-col',
        'lg:flex-nowrap',
        'lg:flex-row-reverse',
        'lg:py-3',
        'lg:mx-auto',
        'lg:flex-row',
        'mb-2',
        'xl:mb-3',
        'typography',
        'lead',
        'tagline',
        'mb-1.5',
        'sm:gap-x-1',
        'md:gap-x-2',
        'lg:gap-x-3',
        'py-1',
        'xl:py-[1.25rem]',
        'py-0.75',
        'px-1',
        'lg:px-1.5',
        'xl:py-1',
        'pt-half',
        'lg:pt-1',
        'pb-1.5',
        'pr-2',
        'lg:pb-2',
        'p-1.5',
        'lg:py-2',
        'lg:basis-2/3',
        'lg:basis-1/3',
        'basis-1/2',
        'md:basis-1/3',
        'lg:basis-1/4',
        'hide',
        'show',
        'max-lg:hidden',
        'max-lg:invisible',
        'mb-half',
        'my-1',
        'xl:gap-2',
        'max-w-[80px]',
        'md:max-w-[180px]',
        'lg:mb-1.5',
        'p-[10px]',
        'mr-1',
        'lg:mr-2',
        'h-[550px]',
        'xl:h-[650px]',
        'lg:min-h-[650px]',
        'lg:h-[60vh]',
        'xl:min-h-[800px]',
        'xl:h-[80vh]',
        'text-base',
        'text-lg',
        'text-sm',
        'max-w-screen-md',
        'max-w-screen-lg',
        'max-w-screen-3xl',
        'max-w-full',
        'mx-auto',
        'mb-qtr',
        'mb-0.75',
        'userform',
        'ui-loader',
        'ui-loaded',
        'flex-wrap',
        'gap-[0.5rem]',
        'w-1/2',
        'md:w-1/2',
        'lg:w-1/4',
        '2xl:p-1',
        'p-half',
        'aspect-[4/3]',
        'w-fit',
        'w-[250px]',
        'p-0.75',
        'bg-secondary',
        'bg-black',
        'lg:align-bottom',
        'lg:align-text-bottom',
        'justify-between',
        'items-center',
        'lg:shrink',
        'lg:justify-end',
        'lg:items-center',
        'lg:grow',
        'flex-col',
        'lg:flex-row',
        'lg:px-2',
        'fixed',
        'justify-end',
        'aspect-square',
        'h-[80px]',
        'w-[80px]',
        'lg:h-[120px]',
        'lg:w-[120px]',
        'xl:h-[180px]',
        'xl:w-[180px]',
        'lg:text-lg',
        'xl:text-xl',
        'my-2',
    ],
    theme: {
        container: {
            center: true,
            padding: '1rem',
        },
        screens: {
            sm: '640px',
            md: '768px', // Narrow width
            lg: '1024px',
            xl: '1200px', // Default width
            '2xl': '1500px',
            '3xl': '1800px', // Wide width
        },
        fontFamily: {
            sans: ['Poppins', 'sans-serif'],
            serif: ['Merriweather', 'serif'],
        },
        fontSize: {
            xs: ['0.687rem', '1rem'],
            sm: ['0.812rem', '1.25rem'],
            base: ['1rem', '1.5rem'], // Paragraph and H6 Mobile
            lg: ['1.125rem', '1.75rem'],
            xl: ['1.25rem', '1.75rem'],
            '2xl': ['1.5rem', '2rem'],
            '3xl': ['1.78rem', '2.25rem'],
            '4xl': ['2rem', '2.75rem'],
            '5xl': ['2.5rem', '1.1'],
            '6xl': ['3rem', '1'],
            '7xl': ['3.75rem', '1'],
            '8xl': ['4.75rem', '1'],
            '9xl': ['5rem', '1'],
            '10xl': ['6.5rem', '1'],
            'fluid-h1': 'calc(1.375rem + 1.5vw)', // Responsive Fluid Typography
            'fluid-h2': 'calc(1.325rem + 0.9vw)',
            'fluid-h3': 'calc(1.3rem + 0.6vw)',
            'fluid-h4': 'calc(1.275rem + 0.3vw)',
            'fluid-h5': 'calc(1.175rem + 0.2vw)',
            'fluid-h6': 'calc(1rem + 0.1vw)',
        },
        spacing: {
            // Spacing based on Foundation spacings e.g. .margin-bottom-1
            0: '0',
            0.75: '0.75rem',
            1: '1rem',
            1.25: '1.25rem',
            1.5: '1.5rem',
            1.75: '1.75rem',
            2: '2rem',
            3: '3rem',
            4: '4rem',
            5: '5rem',
            10: '10rem',
            half: '0.5rem',
            qtr: '0.25rem',
        },
        extend: {
            colors: {
                primary: {
                    light: 'rgb(var(--color-primary-light) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--color-primary) / <alpha-value>)',
                    dark: 'rgb(var(--color-primary-dark) / <alpha-value>)',
                },
                secondary: {
                    light: 'rgb(var(--color-secondary-light) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--color-secondary) / <alpha-value>)',
                    dark: 'rgb(var(--color-secondary-dark) / <alpha-value>)',
                },
                acent1: 'rgb(var(--color-acent1) / <alpha-value>)',
                acent2: 'rgb(var(--color-acent2) / <alpha-value>)',
                lightgrey: 'rgb(var(--color-lightgrey) / <alpha-value>)',
                upper_lightgrey: 'rgb(var(--upper-lightgrey) / <alpha-value>)',
                medium_lightgrey: 'rgb(var(--medium-lightgrey) / <alpha-value>)',
                grey: 'rgb(var(--color-grey) / <alpha-value>)',
                warning: 'rgb(var(--color-warning) / <alpha-value>)',
                danger: 'rgb(var(--color-danger) / <alpha-value>)',
                success: 'rgb(var(--color-success) / <alpha-value>)',
                transparent: 'transparent',
            },
            borderRadius: {
                '4xl': '2rem',
            },
            typography: (theme) => ({
                DEFAULT: {
                    css: {
                        'h1, h2, h3, h4': {
                            marginTop: theme('spacing.half'),
                            marginBottom: theme('spacing.1'),
                        },
                        // Old FontSizes
                        // 'h1, .h1': {
                        //     fontSize: theme('fontSize.fluid-h1'),
                        //     '@screen xl': {
                        //         fontSize: theme('fontSize.5xl[0]'),
                        //     },
                        // },
                        // 'h2, .h2': {
                        //     fontSize: theme('fontSize.fluid-h2'),
                        //     '@screen xl': {
                        //         fontSize: theme('fontSize.4xl[0]'),
                        //     },
                        // },
                        // 'h3, .h3': {
                        //     fontSize: theme('fontSize.fluid-h3'),
                        //     '@screen xl': {
                        //         fontSize: theme('fontSize.3xl[0]'),
                        //     },
                        // },
                        // 'h4, .h4': {
                        //     fontSize: theme('fontSize.fluid-h4'),
                        //     '@screen xl': {
                        //         fontSize: theme('fontSize.2xl[0]'),
                        //     },
                        // },
                        // 'h5, .h5': {
                        //     fontSize: theme('fontSize.lg[0]'),
                        //     '@screen xl': {
                        //         fontSize: theme('fontSize.xl[0]'),
                        //     },
                        // },
                        // 'h6, .h6': {
                        //     fontSize: theme('fontSize.base[0]'),
                        //     '@screen xl': {
                        //         fontSize: theme('fontSize.lg[0]'),
                        //     },
                        // },

                        'h1, .h1': {
                            fontSize: '48px',
                            '@screen xl': {
                                fontSize: '28px',
                            },
                        },
                        'h2, .h2': {
                            fontSize: '32px',
                            '@screen xl': {
                                fontSize: '24px',
                            },
                        },
                        'h3, .h3': {
                            fontSize: '28px',
                            '@screen xl': {
                                fontSize: '23px',
                            },
                        },
                        'h4, .h4': {
                            fontSize: '24',
                            '@screen xl': {
                                fontSize: '21px',
                            },
                        },
                        'h5, .h5': {
                            fontSize: '20px',
                            '@screen xl': {
                                fontSize: '18px',
                            },
                        },
                        'h6, .h6': {
                            fontSize: '18px',
                            '@screen xl': {
                                fontSize: '16px',
                            },
                        },
                    },
                },
            }),
        },
    },
    plugins: [
        require('@tailwindcss/typography')({
            className: 'typography',
        }),
        require('@tailwindcss/forms'),
    ],
};
