<?php
/**
* Title: Packages
* Slug: tzo/packages
* Description: A page block pattern to introduce the company's packages.
* Categories: layout
* Inserter: yes
*/
?>

<!-- wp:acf/introduction {"name":"acf/introduction","data":{"field_664c2ed5302a7":"Packages","field_664c2eee6009d":"Optional Tagline","field_664c2ed530307":"\u003cp class=\u0022lead\u0022\u003eNullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec id elit non mi porta gravida at eget metus.\u003c/p\u003e\r\nNullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec id elit non mi porta gravida at eget metus.","field_664c2ed53036d":{"title":"Learn More","url":"#","target":""},"field_664c2f3d5188f":{"title":"","url":"","target":""},"field_664c2ed5303d5":"0","field_664c2f5f333bd":"1"},"mode":"auto"} /-->

<!-- wp:acf/content-carousel-slider {"name":"acf/content-carousel-slider","data":{"title":"Packages","_title":"field_64d3ede089f91","button_link":{"title":"View More","url":"#","target":""},"_button_link":"field_64d3ede589f92","carousel_items_0_item_title":"Package One","_carousel_items_0_item_title":"field_64d3ee5789f94","carousel_items_0_item_description":"Donec id elit non mi porta gravida at eget metus.","_carousel_items_0_item_description":"field_64d3ee7189f95","carousel_items_0_item_image":" ","_carousel_items_0_item_image":"field_64d3ee8e89f96","carousel_items_0_item_link":{"title":"Learn More","url":"#","target":""},"_carousel_items_0_item_link":"field_64d3ee9789f97","carousel_items_1_item_title":"Package Two","_carousel_items_1_item_title":"field_64d3ee5789f94","carousel_items_1_item_description":"Donec id elit non mi porta gravida at eget metus.","_carousel_items_1_item_description":"field_64d3ee7189f95","carousel_items_1_item_image":" ","_carousel_items_1_item_image":"field_64d3ee8e89f96","carousel_items_1_item_link":{"title":"Learn More","url":"#","target":""},"_carousel_items_1_item_link":"field_64d3ee9789f97","carousel_items_2_item_title":"Package Three","_carousel_items_2_item_title":"field_64d3ee5789f94","carousel_items_2_item_description":"Donec id elit non mi porta gravida at eget metus.","_carousel_items_2_item_description":"field_64d3ee7189f95","carousel_items_2_item_image":" ","_carousel_items_2_item_image":"field_64d3ee8e89f96","carousel_items_2_item_link":{"title":"Learn More","url":"#","target":""},"_carousel_items_2_item_link":"field_64d3ee9789f97","carousel_items_3_item_title":"Package Four","_carousel_items_3_item_title":"field_64d3ee5789f94","carousel_items_3_item_description":"Donec id elit non mi porta gravida at eget metus.","_carousel_items_3_item_description":"field_64d3ee7189f95","carousel_items_3_item_image":" ","_carousel_items_3_item_image":"field_64d3ee8e89f96","carousel_items_3_item_link":{"title":"Learn More","url":"#","target":""},"_carousel_items_3_item_link":"field_64d3ee9789f97","carousel_items_4_item_title":"Package Five","_carousel_items_4_item_title":"field_64d3ee5789f94","carousel_items_4_item_description":"Donec id elit non mi porta gravida at eget metus.","_carousel_items_4_item_description":"field_64d3ee7189f95","carousel_items_4_item_image":" ","_carousel_items_4_item_image":"field_64d3ee8e89f96","carousel_items_4_item_link":{"title":"Learn More","url":"#","target":""},"_carousel_items_4_item_link":"field_64d3ee9789f97","carousel_items":5,"_carousel_items":"field_64d3ee2989f93","display_as_slider":"0","_display_as_slider":"field_64d3eecd89f99","thumbnail_nav":"0","_thumbnail_nav":"field_64d3ef0189f9a","remove_bottom_margin":"0","_remove_bottom_margin":"field_64d3ef2289f9b"},"mode":"auto"} /-->