<?php
/**
* Title: Style Guide
* Slug: tzo/style-guide
* Description: A page block pattern to list out all the company's blocks.
* Categories: layout
* Inserter: yes
*/
?>
<!-- wp:acf/introduction {"name":"acf/introduction","data":{"title":"Introduction Block - Narrow Centered","_title":"field_664c2ed5302a7","tagline":"Tagline","_tagline":"field_664c2eee6009d","html_content":"Aenean lacinia bibendum nulla sed consectetur. Maecenas sed diam eget risus varius blandit sit amet non magna. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.","_html_content":"field_664c2ed530307","link":{"title":"Button","url":"#","target":""},"_link":"field_664c2ed53036d","optional_link":{"title":"Button Two","url":"#","target":""},"_optional_link":"field_664c2f3d5188f","remove_bottom_margin":"0","_remove_bottom_margin":"field_664c2ed5303d5","align_center":"1","_align_center":"field_664c2f5f333bd"},"mode":"auto","className":"is-style-narrow"} /-->

<!-- wp:acf/html-content {"name":"acf/html-content","data":{"title":"HTML Content - Narrow","_title":"field_64b57c83ee302","html_content":"Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec id elit non mi porta gravida at eget metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Cras justo odio, dapibus ac facilisis in, egestas eget quam.\r\n\r\nNullam id dolor id nibh ultricies vehicula ut id elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id dolor id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at lobortis.","_html_content":"field_64b5788faf35d","link":{"title":"Button","url":"#","target":"_blank"},"_link":"field_64b57c9dee303","remove_bottom_margin":"0","_remove_bottom_margin":"field_64b96d817d867"},"mode":"auto","className":"is-style-narrow"} /-->

<!-- wp:acf/embed {"name":"acf/embed","data":{"heading":"Embed Block Narrow","_heading":"field_64cd4e9d28dbf","embed":"\u003cstyle\u003e.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }\u003c/style\u003e\u003cdiv class='embed-container'\u003e\u003ciframe src='https://www.youtube.com/embed/GpcaJQ40q1Y' frameborder='0' allowfullscreen\u003e\u003c/iframe\u003e\u003c/div\u003e","_embed":"field_64cd4e7b28dbe","remove_bottom_margin":"0","_remove_bottom_margin":"field_64cd4ebf28dc0"},"mode":"auto","className":"is-style-narrow"} /-->

<!-- wp:acf/embed {"name":"acf/embed","data":{"heading":"","_heading":"field_64cd4e9d28dbf","embed":"[gravityform id=\u00221\u0022 title=\u0022true\u0022]","_embed":"field_64cd4e7b28dbe","remove_bottom_margin":"0","_remove_bottom_margin":"field_64cd4ebf28dc0"},"mode":"auto","className":"is-style-narrow"} /-->

<!-- wp:columns {"className":"is-style-narrow"} -->
<div class="wp-block-columns is-style-narrow"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:acf/html-content {"name":"acf/html-content","data":{"title":"Core Columns 1/2 Narrow","_title":"field_64b57c83ee302","html_content":"Curabitur blandit tempus porttitor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.","_html_content":"field_64b5788faf35d","link":{"title":"Button","url":"#","target":""},"_link":"field_64b57c9dee303","remove_bottom_margin":"0","_remove_bottom_margin":"field_64b96d817d867"},"mode":"auto","className":"is-style-default"} /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:acf/html-content {"name":"acf/html-content","data":{"title":"Core Columns 1/2 Narrow","_title":"field_64b57c83ee302","html_content":"Curabitur blandit tempus porttitor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.","_html_content":"field_64b5788faf35d","link":{"title":"Button","url":"#","target":""},"_link":"field_64b57c9dee303","remove_bottom_margin":"0","_remove_bottom_margin":"field_64b96d817d867"},"mode":"auto"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"verticalAlignment":"center","width":"33.33%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:33.33%"><!-- wp:acf/html-content {"name":"acf/html-content","data":{"title":"Core Columns 1/3 Default Align Middle","_title":"field_64b57c83ee302","html_content":"Etiam porta sem malesuada magna mollis euismod. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec ullamcorper nulla non metus auctor fringilla. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.","_html_content":"field_64b5788faf35d","link":{"title":"Button","url":"#","target":""},"_link":"field_64b57c9dee303","remove_bottom_margin":"0","_remove_bottom_margin":"field_64b96d817d867"},"mode":"auto"} /--></div>
<!-- /wp:column -->

<!-- wp:column {"width":"66.66%"} -->
<div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:acf/highlight {"name":"acf/highlight","data":{"title":"Core Columns 2/3 Default Align Middle","_title":"field_64c9543896ade","subtitle":"Subtitle","_subtitle":"field_64c9543896b35","image":13,"_image":"field_64c9543896be1","background_video_url":"","_background_video_url":"field_665a3a16782b5","html_content":"","_html_content":"field_64c9543896c36","caption_alignment":"caption-left","_caption_alignment":"field_64c9543896cdc","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c9543896dc9","optional_button_link":"","_optional_button_link":"field_64c9543896e31","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c9543896e81"},"mode":"auto"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:acf/button {"name":"acf/button","data":{"button":{"title":"Button","url":"#","target":""},"_button":"field_66a96074ce3f0","button_style":"primary","_button_style":"field_66aa8a84ef9bc","button_size":"default","_button_size":"field_66aa89299f61b","secondary_button":{"title":"Button Secondary","url":"#","target":""},"_secondary_button":"field_66aa8f0ff1768","secondary_button_style":"hollow","_secondary_button_style":"field_66aa8f28f1769","secondary_button_size":"default","_secondary_button_size":"field_66aa8f50f176a","heading":"Buttons","_heading":"field_66b0d6f6348b6","button_alignment":"justify-start","_button_alignment":"field_66aa95f8019f5","remove_bottom_margin":"0","_remove_bottom_margin":"field_66a960c680039"},"mode":"auto"} /-->

<!-- wp:acf/file-download {"name":"acf/file-download","data":{"title":"Downloadables","_title":"field_66b022e2eb217","file_link":16,"_file_link":"field_66b0235b3e215","custom_filename":"","_custom_filename":"field_66b0294a3d62e","opens_new_window":"0","_opens_new_window":"field_66b02832e0b2a","show_download_button":"1","_show_download_button":"field_66b02857c246d","remove_bottom_margin":"1","_remove_bottom_margin":"field_66b022e2eb45c"},"mode":"auto"} /-->

<!-- wp:acf/file-download {"name":"acf/file-download","data":{"title":"","_title":"field_66b022e2eb217","file_link":16,"_file_link":"field_66b0235b3e215","custom_filename":"Custom Filename","_custom_filename":"field_66b0294a3d62e","opens_new_window":"0","_opens_new_window":"field_66b02832e0b2a","show_download_button":"1","_show_download_button":"field_66b02857c246d","remove_bottom_margin":"1","_remove_bottom_margin":"field_66b022e2eb45c"},"mode":"auto"} /-->

<!-- wp:acf/file-download {"name":"acf/file-download","data":{"title":"","_title":"field_66b022e2eb217","file_link":16,"_file_link":"field_66b0235b3e215","custom_filename":"","_custom_filename":"field_66b0294a3d62e","opens_new_window":"0","_opens_new_window":"field_66b02832e0b2a","show_download_button":"0","_show_download_button":"field_66b02857c246d","remove_bottom_margin":"0","_remove_bottom_margin":"field_66b022e2eb45c"},"mode":"auto"} /-->

<!-- wp:acf/toggle-content {"name":"acf/toggle-content","data":{"content":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Nullam id dolor id nibh ultricies vehicula ut id elit.","_content":"field_66a853c5b4184","heading":"Toggle Content Block - Default","_heading":"field_66b0d4213d6a9","display_as_link":"0","_display_as_link":"field_66a91146a0de4","use_custom_button_or_link_text":"0","_use_custom_button_or_link_text":"field_66a91017a0de3"},"mode":"auto"} /-->

<!-- wp:acf/html-content {"name":"acf/html-content","data":{"title":"Tables - Default \u0026 Wide Centered","_title":"field_64b57c83ee302","html_content":"","_html_content":"field_64b5788faf35d","link":"","_link":"field_64b57c9dee303","remove_bottom_margin":"1","_remove_bottom_margin":"field_64b96d817d867"},"mode":"auto"} /-->

<!-- wp:table -->
<figure class="wp-block-table"><table class="has-fixed-layout"><tbody><tr><td>Vehicula Cursus</td><td>Tellus Ligula</td></tr><tr><td>Adipiscing Tellus</td><td><br>Pellentesque Tellus</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:table {"className":"is-style-wide"} -->
<figure class="wp-block-table is-style-wide"><table class="has-fixed-layout"><thead><tr><th class="has-text-align-center" data-align="center">Heading 1</th><th class="has-text-align-center" data-align="center">Heading 2</th><th class="has-text-align-center" data-align="center">Heading 3</th><th class="has-text-align-center" data-align="center">Heading 4</th><th class="has-text-align-center" data-align="center">Heading 5</th></tr></thead><tbody><tr><td class="has-text-align-center" data-align="center">Justo Fringilla</td><td class="has-text-align-center" data-align="center">Etiam</td><td class="has-text-align-center" data-align="center">Malesuada</td><td class="has-text-align-center" data-align="center">Commodo</td><td class="has-text-align-center" data-align="center">Fringilla</td></tr><tr><td class="has-text-align-center" data-align="center">Commodo Fusce</td><td class="has-text-align-center" data-align="center">Bibendum Malesuada</td><td class="has-text-align-center" data-align="center">Purus Vulputate</td><td class="has-text-align-center" data-align="center">Ullamcorper Magna</td><td class="has-text-align-center" data-align="center">Nibh</td></tr><tr><td class="has-text-align-center" data-align="center">Ipsum</td><td class="has-text-align-center" data-align="center">Fusce</td><td class="has-text-align-center" data-align="center">Consectetur Sem</td><td class="has-text-align-center" data-align="center">Malesuada</td><td class="has-text-align-center" data-align="center">Ligula Parturient</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:acf/call-to-action {"name":"acf/call-to-action","data":{"title":"Call to Action - Default","_title":"field_64b6e61b62c08","html_content":"Aenean lacinia bibendum nulla sed consectetur. Donec ullamcorper nulla non metus auctor fringilla. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Cras mattis consectetur purus sit amet fermentum. Donec sed odio dui. Nullam id dolor id nibh ultricies vehicula ut id elit.","_html_content":"field_64b6e75abb6a9","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64b6e76fbb6aa","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_64b6e782bb6ab","alt_mode":"0","_alt_mode":"field_64b6ec2ffe888","remove_bottom_margin":"0","_remove_bottom_margin":"field_64b968e046438"},"mode":"auto","className":"is-style-default"} /-->

<!-- wp:acf/call-to-action {"name":"acf/call-to-action","data":{"title":"Call to Action - Wide Alternate","_title":"field_64b6e61b62c08","html_content":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae elit libero, a pharetra augue. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","_html_content":"field_64b6e75abb6a9","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64b6e76fbb6aa","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_64b6e782bb6ab","alt_mode":"1","_alt_mode":"field_64b6ec2ffe888","remove_bottom_margin":"0","_remove_bottom_margin":"field_64b968e046438"},"mode":"auto","className":"is-style-wide"} /-->

<!-- wp:acf/half-box {"name":"acf/half-box","data":{"title":"Halfbox - Full","_title":"field_64c8ebceb4148","tagline":"Parturient Adipiscing Fusce","_tagline":"field_64c8ebf34ce09","image":13,"_image":"field_64c8eca74ce0a","background_video_url":"","_background_video_url":"field_665a3979158b4","html_content":"Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur. Curabitur blandit tempus porttitor. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.\r\n\r\nDonec id elit non mi porta gravida at eget metus. Donec ullamcorper nulla non metus auctor fringilla. Etiam porta sem malesuada magna mollis euismod. Cras mattis consectetur purus sit amet fermentum. Nullam id dolor id nibh ultricies vehicula ut id elit. Maecenas sed diam eget risus varius blandit sit amet non magna.","_html_content":"field_64c8ebceb41ba","caption_alignment":"0","_caption_alignment":"field_64c8ed3e8f02c","box_mode":"0","_box_mode":"field_64c8f18d06707","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c8ebceb4242","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_64c8ebceb4294","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c8ebceb43ab"},"mode":"auto","className":"is-style-full"} /-->

<!-- wp:acf/half-box {"name":"acf/half-box","data":{"title":"Halfbox - Wide Reverse w/ Video","_title":"field_64c8ebceb4148","tagline":"Tagline","_tagline":"field_64c8ebf34ce09","image":17,"_image":"field_64c8eca74ce0a","background_video_url":"https://player.vimeo.com/progressive_redirect/playback/815090665/rendition/720p/file.mp4?loc=external\u0026signature=1c4c7bd74254e6fc55231e63ecdf88d2ea2c3f893f2f7377b94144e57d854314","_background_video_url":"field_665a3979158b4","html_content":"Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Nullam quis risus eget urna mollis ornare vel eu leo. Donec id elit non mi porta gravida at eget metus.\r\n\r\nCras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Etiam porta sem malesuada magna mollis euismod. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Nulla vitae elit libero, a pharetra augue.","_html_content":"field_64c8ebceb41ba","caption_alignment":"1","_caption_alignment":"field_64c8ed3e8f02c","box_mode":"0","_box_mode":"field_64c8f18d06707","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c8ebceb4242","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_64c8ebceb4294","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c8ebceb43ab"},"mode":"auto","className":"is-style-wide"} /-->

<!-- wp:acf/pathways {"name":"acf/pathways","data":{"title":"Pathways - Default Articles","_title":"field_64c96c4e757ab","pathways_items_0_title":"Amet Etiam","_pathways_items_0_title":"field_64c96cd5bfa5c","pathways_items_0_image":17,"_pathways_items_0_image":"field_64c96ceabfa5d","pathways_items_0_description":"Cras justo odio, dapibus ac facilisis in, egestas eget quam. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Nullam id dolor id nibh ultricies vehicula ut id elit.","_pathways_items_0_description":"field_64c96d07bfa5e","pathways_items_0_link":{"title":"Link","url":"#","target":""},"_pathways_items_0_link":"field_64c96d29bfa5f","pathways_items_1_title":"Ultricies Inceptos","_pathways_items_1_title":"field_64c96cd5bfa5c","pathways_items_1_image":15,"_pathways_items_1_image":"field_64c96ceabfa5d","pathways_items_1_description":"Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.","_pathways_items_1_description":"field_64c96d07bfa5e","pathways_items_1_link":{"title":"Link","url":"#","target":""},"_pathways_items_1_link":"field_64c96d29bfa5f","pathways_items_2_title":"Nullam Sit","_pathways_items_2_title":"field_64c96cd5bfa5c","pathways_items_2_image":19,"_pathways_items_2_image":"field_64c96ceabfa5d","pathways_items_2_description":"Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper.","_pathways_items_2_description":"field_64c96d07bfa5e","pathways_items_2_link":"","_pathways_items_2_link":"field_64c96d29bfa5f","pathways_items_3_title":"Condimentum Sollicitudin","_pathways_items_3_title":"field_64c96cd5bfa5c","pathways_items_3_image":"","_pathways_items_3_image":"field_64c96ceabfa5d","pathways_items_3_description":"","_pathways_items_3_description":"field_64c96d07bfa5e","pathways_items_3_link":{"title":"Link","url":"#","target":""},"_pathways_items_3_link":"field_64c96d29bfa5f","pathways_items":4,"_pathways_items":"field_64c96c4e75816","show_more_loader":"0","_show_more_loader":"field_6626ad29fb572","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c96c4e759d4","layout_type":"is-article","_layout_type":"field_64c96c4e758cc","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c96c4e75ab3"},"mode":"auto"} /-->

<!-- wp:acf/pathways {"name":"acf/pathways","data":{"title":"Pathways - Feature Wide","_title":"field_64c96c4e757ab","pathways_items_0_title":"Magna Commodo","_pathways_items_0_title":"field_64c96cd5bfa5c","pathways_items_0_image":13,"_pathways_items_0_image":"field_64c96ceabfa5d","pathways_items_0_description":"Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Nulla vitae elit libero, a pharetra augue.","_pathways_items_0_description":"field_64c96d07bfa5e","pathways_items_0_link":{"title":"Link","url":"#","target":""},"_pathways_items_0_link":"field_64c96d29bfa5f","pathways_items_1_title":"Ridiculus Nullam","_pathways_items_1_title":"field_64c96cd5bfa5c","pathways_items_1_image":"","_pathways_items_1_image":"field_64c96ceabfa5d","pathways_items_1_description":"Nullam quis risus eget urna mollis ornare vel eu leo. Maecenas faucibus mollis interdum. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.","_pathways_items_1_description":"field_64c96d07bfa5e","pathways_items_1_link":"","_pathways_items_1_link":"field_64c96d29bfa5f","pathways_items_2_title":"Parturient Risus","_pathways_items_2_title":"field_64c96cd5bfa5c","pathways_items_2_image":15,"_pathways_items_2_image":"field_64c96ceabfa5d","pathways_items_2_description":"","_pathways_items_2_description":"field_64c96d07bfa5e","pathways_items_2_link":{"title":"Link","url":"#","target":""},"_pathways_items_2_link":"field_64c96d29bfa5f","pathways_items_3_title":"Fermentum Condimentum","_pathways_items_3_title":"field_64c96cd5bfa5c","pathways_items_3_image":"","_pathways_items_3_image":"field_64c96ceabfa5d","pathways_items_3_description":"","_pathways_items_3_description":"field_64c96d07bfa5e","pathways_items_3_link":"","_pathways_items_3_link":"field_64c96d29bfa5f","pathways_items":4,"_pathways_items":"field_64c96c4e75816","show_more_loader":"0","_show_more_loader":"field_6626ad29fb572","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c96c4e759d4","layout_type":"is-feature","_layout_type":"field_64c96c4e758cc","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c96c4e75ab3"},"mode":"auto","className":"is-style-wide"} /-->

<!-- wp:acf/related-articles {"name":"acf/related-articles","data":{"title":"Related Articles - Default Articles","_title":"field_64caaabbc6132","count":"0","_count":"field_64caaad1c6133","categories":"","_categories":"field_64caaae4c6134","tags":"","_tags":"field_64caab12c6135","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64caab37c6136","articles":"","_articles":"field_64caab49c6137","layout_type":"is-article","_layout_type":"field_64caab85c6138","remove_bottom_margin":"0","_remove_bottom_margin":"field_64caaba6c6139"},"mode":"auto"} /-->

<!-- wp:acf/related-articles {"name":"acf/related-articles","data":{"title":"Related Articles - Wide Feature","_title":"field_64caaabbc6132","count":"0","_count":"field_64caaad1c6133","categories":"","_categories":"field_64caaae4c6134","tags":"","_tags":"field_64caab12c6135","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64caab37c6136","articles":"","_articles":"field_64caab49c6137","layout_type":"is-feature","_layout_type":"field_64caab85c6138","remove_bottom_margin":"0","_remove_bottom_margin":"field_64caaba6c6139"},"mode":"auto","className":"is-style-wide"} /-->

<!-- wp:acf/related-articles {"name":"acf/related-articles","data":{"title":"Related Articles - Full Gallery","_title":"field_64caaabbc6132","count":"0","_count":"field_64caaad1c6133","categories":"","_categories":"field_64caaae4c6134","tags":"","_tags":"field_64caab12c6135","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64caab37c6136","articles":"","_articles":"field_64caab49c6137","layout_type":"is-gallery","_layout_type":"field_64caab85c6138","remove_bottom_margin":"0","_remove_bottom_margin":"field_64caaba6c6139"},"mode":"auto","className":"is-style-full"} /-->

<!-- wp:acf/accordion-tabs {"name":"acf/accordion-tabs","data":{"accordion_items_0_title":"Elit Justo Fermentum","_accordion_items_0_title":"field_64d1246709589","accordion_items_0_content":"Etiam porta sem malesuada magna mollis euismod. Sed posuere consectetur est at lobortis. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur.","_accordion_items_0_content":"field_64d1246e0958a","accordion_items_1_title":"Etiam Nullam","_accordion_items_1_title":"field_64d1246709589","accordion_items_1_content":"Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec id elit non mi porta gravida at eget metus. Curabitur blandit tempus porttitor.","_accordion_items_1_content":"field_64d1246e0958a","accordion_items":2,"_accordion_items":"field_64d1245309588","the_heading":"Accordion - Narrow","_the_heading":"field_64d124ac0958c","link":{"title":"Button","url":"#","target":""},"_link":"field_64d124dc0958d","open_first_item":"0","_open_first_item":"field_64d124f70958e","display_as_tabs":"0","_display_as_tabs":"field_64d1251b0958f","remove_bottom_margin":"0","_remove_bottom_margin":"field_64d1252c09590"},"mode":"auto","className":"is-style-narrow"} /-->

<!-- wp:acf/accordion-tabs {"name":"acf/accordion-tabs","data":{"accordion_items_0_title":"Tellus Inceptos","_accordion_items_0_title":"field_64d1246709589","accordion_items_0_content":"Nullam quis risus eget urna mollis ornare vel eu leo. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.","_accordion_items_0_content":"field_64d1246e0958a","accordion_items_1_title":"Ligula Ullamcorper","_accordion_items_1_title":"field_64d1246709589","accordion_items_1_content":"Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Maecenas faucibus mollis interdum. Maecenas sed diam eget risus varius blandit sit amet non magna.","_accordion_items_1_content":"field_64d1246e0958a","accordion_items":2,"_accordion_items":"field_64d1245309588","the_heading":"Tabs - Default","_the_heading":"field_64d124ac0958c","link":{"title":"Button","url":"#","target":""},"_link":"field_64d124dc0958d","open_first_item":"0","_open_first_item":"field_64d124f70958e","display_as_tabs":"1","_display_as_tabs":"field_64d1251b0958f","remove_bottom_margin":"0","_remove_bottom_margin":"field_64d1252c09590"},"mode":"auto"} /-->

<!-- wp:acf/image-gallery {"name":"acf/image-gallery","data":{"select_gallery":70,"_select_gallery":"field_64cd1ada63804","content":"","_content":"field_64cd1b2d63805","show_image_titles":"0","_show_image_titles":"field_64cd1b7463806","hide_gallery_title":"0","_hide_gallery_title":"field_64cd1b8e63807","remove_bottom_margin":"0","_remove_bottom_margin":"field_64cd1ba263808"},"mode":"auto"} /-->

<!-- wp:acf/highlight {"name":"acf/highlight","data":{"title":"Highlight - Default","_title":"field_64c9543896ade","subtitle":"Subtitle","_subtitle":"field_64c9543896b35","image":13,"_image":"field_64c9543896be1","background_video_url":"","_background_video_url":"field_665a3a16782b5","html_content":"Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.","_html_content":"field_64c9543896c36","caption_alignment":"caption-default","_caption_alignment":"field_64c9543896cdc","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c9543896dc9","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_64c9543896e31","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c9543896e81"},"mode":"auto"} /-->

<!-- wp:acf/highlight {"name":"acf/highlight","data":{"title":"Highlight - Full Center w/ Video","_title":"field_64c9543896ade","subtitle":"Subtitle","_subtitle":"field_64c9543896b35","image":15,"_image":"field_64c9543896be1","background_video_url":"https://player.vimeo.com/progressive_redirect/playback/815090665/rendition/720p/file.mp4?loc=external\u0026signature=1c4c7bd74254e6fc55231e63ecdf88d2ea2c3f893f2f7377b94144e57d854314","_background_video_url":"field_665a3a16782b5","html_content":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla.","_html_content":"field_64c9543896c36","caption_alignment":"caption-center","_caption_alignment":"field_64c9543896cdc","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64c9543896dc9","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_64c9543896e31","remove_bottom_margin":"0","_remove_bottom_margin":"field_64c9543896e81"},"mode":"auto","className":"is-style-full"} /-->

<!-- wp:acf/html-content {"name":"acf/html-content","data":{"title":"Separator - Default","_title":"field_64b57c83ee302","html_content":"","_html_content":"field_64b5788faf35d","link":"","_link":"field_64b57c9dee303","remove_bottom_margin":"1","_remove_bottom_margin":"field_64b96d817d867"},"mode":"auto"} /-->

<!-- wp:acf/separator {"name":"acf/separator","mode":"auto"} /-->

<!-- wp:acf/logos {"name":"acf/logos","data":{"title":"Logos - Default","_title":"field_64d174b06a738","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64d174d56a739","logo_items_0_logo_title":"Fermentum Quam","_logo_items_0_logo_title":"field_64d175976a73c","logo_items_0_logo_image":16,"_logo_items_0_logo_image":"field_64d175c56a73d","logo_items_0_logo_desc":"Etiam porta sem malesuada magna mollis euismod.","_logo_items_0_logo_desc":"field_64d175ec6a73e","logo_items_0_logo_link":{"title":"Link","url":"#","target":""},"_logo_items_0_logo_link":"field_64d176076a73f","logo_items_1_logo_title":"Euismod Lorem","_logo_items_1_logo_title":"field_64d175976a73c","logo_items_1_logo_image":18,"_logo_items_1_logo_image":"field_64d175c56a73d","logo_items_1_logo_desc":"Donec id elit non mi porta gravida at eget metus.","_logo_items_1_logo_desc":"field_64d175ec6a73e","logo_items_1_logo_link":{"title":"Link","url":"#","target":""},"_logo_items_1_logo_link":"field_64d176076a73f","logo_items_2_logo_title":"Dolor Dapibus","_logo_items_2_logo_title":"field_64d175976a73c","logo_items_2_logo_image":16,"_logo_items_2_logo_image":"field_64d175c56a73d","logo_items_2_logo_desc":"Etiam porta sem malesuada magna mollis euismod.","_logo_items_2_logo_desc":"field_64d175ec6a73e","logo_items_2_logo_link":{"title":"Link","url":"#","target":""},"_logo_items_2_logo_link":"field_64d176076a73f","logo_items":3,"_logo_items":"field_64d174ec6a73b","remove_bottom_margin":"0","_remove_bottom_margin":"field_64d176366a741"},"mode":"auto"} /-->

<!-- wp:acf/content-carousel-slider {"name":"acf/content-carousel-slider","data":{"title":"Content Carousel - Wide","_title":"field_64d3ede089f91","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64d3ede589f92","carousel_items_0_item_title":"Cras QuamCras Quam","_carousel_items_0_item_title":"field_64d3ee5789f94","carousel_items_0_item_description":"Sed posuere consectetur est at lobortis.","_carousel_items_0_item_description":"field_64d3ee7189f95","carousel_items_0_item_image":15,"_carousel_items_0_item_image":"field_64d3ee8e89f96","carousel_items_0_item_vimeo_id":"","_carousel_items_0_item_vimeo_id":"field_677d4fbf8e86d","carousel_items_0_item_link":{"title":"Link","url":"#","target":""},"_carousel_items_0_item_link":"field_64d3ee9789f97","carousel_items_1_item_title":"Vehicula Fringilla","_carousel_items_1_item_title":"field_64d3ee5789f94","carousel_items_1_item_description":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","_carousel_items_1_item_description":"field_64d3ee7189f95","carousel_items_1_item_image":14,"_carousel_items_1_item_image":"field_64d3ee8e89f96","carousel_items_1_item_vimeo_id":"452258957","_carousel_items_1_item_vimeo_id":"field_677d4fbf8e86d","carousel_items_1_item_link":{"title":"Link","url":"#","target":""},"_carousel_items_1_item_link":"field_64d3ee9789f97","carousel_items_2_item_title":"Adipiscing Dapibus Elit","_carousel_items_2_item_title":"field_64d3ee5789f94","carousel_items_2_item_description":"Nullam id dolor id nibh ultricies vehicula ut id elit.","_carousel_items_2_item_description":"field_64d3ee7189f95","carousel_items_2_item_image":13,"_carousel_items_2_item_image":"field_64d3ee8e89f96","carousel_items_2_item_vimeo_id":"","_carousel_items_2_item_vimeo_id":"field_677d4fbf8e86d","carousel_items_2_item_link":{"title":"Link","url":"#","target":""},"_carousel_items_2_item_link":"field_64d3ee9789f97","carousel_items_3_item_title":"Cras Quam","_carousel_items_3_item_title":"field_64d3ee5789f94","carousel_items_3_item_description":"Morbi leo risus, porta ac consectetur ac, vestibulum at eros.","_carousel_items_3_item_description":"field_64d3ee7189f95","carousel_items_3_item_image":19,"_carousel_items_3_item_image":"field_64d3ee8e89f96","carousel_items_3_item_vimeo_id":"","_carousel_items_3_item_vimeo_id":"field_677d4fbf8e86d","carousel_items_3_item_link":{"title":"Link","url":"#","target":""},"_carousel_items_3_item_link":"field_64d3ee9789f97","carousel_items":4,"_carousel_items":"field_64d3ee2989f93","display_as_slider":"0","_display_as_slider":"field_64d3eecd89f99","thumbnail_nav":"0","_thumbnail_nav":"field_64d3ef0189f9a","remove_bottom_margin":"0","_remove_bottom_margin":"field_64d3ef2289f9b"},"mode":"auto","className":"is-style-wide"} /-->

<!-- wp:acf/content-carousel-slider {"name":"acf/content-carousel-slider","data":{"title":"Content Slider - Default w/ Thumbnail Navigation","_title":"field_64d3ede089f91","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_64d3ede589f92","carousel_items_0_item_title":"Parturient Lorem","_carousel_items_0_item_title":"field_64d3ee5789f94","carousel_items_0_item_description":"Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum.","_carousel_items_0_item_description":"field_64d3ee7189f95","carousel_items_0_item_image":13,"_carousel_items_0_item_image":"field_64d3ee8e89f96","carousel_items_0_item_vimeo_id":"","_carousel_items_0_item_vimeo_id":"field_677d4fbf8e86d","carousel_items_0_item_link":{"title":"Link","url":"#","target":""},"_carousel_items_0_item_link":"field_64d3ee9789f97","carousel_items_1_item_title":"Venenatis Commodo","_carousel_items_1_item_title":"field_64d3ee5789f94","carousel_items_1_item_description":"Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Aenean lacinia bibendum nulla sed consectetur.","_carousel_items_1_item_description":"field_64d3ee7189f95","carousel_items_1_item_image":19,"_carousel_items_1_item_image":"field_64d3ee8e89f96","carousel_items_1_item_vimeo_id":"","_carousel_items_1_item_vimeo_id":"field_677d4fbf8e86d","carousel_items_1_item_link":{"title":"Link","url":"#","target":""},"_carousel_items_1_item_link":"field_64d3ee9789f97","carousel_items":2,"_carousel_items":"field_64d3ee2989f93","display_as_slider":"1","_display_as_slider":"field_64d3eecd89f99","thumbnail_nav":"1","_thumbnail_nav":"field_64d3ef0189f9a","remove_bottom_margin":"0","_remove_bottom_margin":"field_64d3ef2289f9b"},"mode":"auto"} /-->

<!-- wp:acf/testimonials {"name":"acf/testimonials","data":{"title":"Testimonials - Narrow","_title":"field_66a853e256c16","testimonials":["73"],"_testimonials":"field_64ca91e1dd89a"},"mode":"auto","className":"is-style-narrow"} /-->

<!-- wp:acf/stats {"name":"acf/stats","data":{"title":"Stats - Default","_title":"field_6704acaa732b6","tagline":"Tagline","_tagline":"field_6704ad6c4ac58","stats_items_0_label":"Clicks","_stats_items_0_label":"field_6704acaa76964","stats_items_0_value_prefix":"+","_stats_items_0_value_prefix":"field_67085e7d10ce9","stats_items_0_value":"10","_stats_items_0_value":"field_6704acaa77100","stats_items_0_value_suffix":"%","_stats_items_0_value_suffix":"field_67085eae10cea","stats_items_1_label":"Revenue","_stats_items_1_label":"field_6704acaa76964","stats_items_1_value_prefix":"$","_stats_items_1_value_prefix":"field_67085e7d10ce9","stats_items_1_value":"30","_stats_items_1_value":"field_6704acaa77100","stats_items_1_value_suffix":"M","_stats_items_1_value_suffix":"field_67085eae10cea","stats_items_2_label":"Engagement","_stats_items_2_label":"field_6704acaa76964","stats_items_2_value_prefix":"","_stats_items_2_value_prefix":"field_67085e7d10ce9","stats_items_2_value":"2","_stats_items_2_value":"field_6704acaa77100","stats_items_2_value_suffix":"X","_stats_items_2_value_suffix":"field_67085eae10cea","stats_items":3,"_stats_items":"field_6704acaa7363c","html_content":"Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.","_html_content":"field_6704ad7c2e3b8","button_link":{"title":"Button","url":"#","target":""},"_button_link":"field_6704acaa73e75","optional_button_link":{"title":"Secondary Button","url":"#","target":""},"_optional_button_link":"field_6704ad4a78d3b","remove_bottom_margin":"0","_remove_bottom_margin":"field_6704acaa7466f"},"mode":"auto"} /-->